version: '3.8'

services:
  frontend:
    build: .
    container_name: innovatech-frontend-app
    ports:
      - "80:5000" # Mapea el puerto HTTP estándar al 5000 de Flask
    environment:
      - BACKEND_URL=http://10.0.128.0:3000  # O la IP privada exacta que tenga tu instancia Backend
    restart: always
