name: CI/CD Frontend Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v3

      - name: Desplegar en EC2 Frontend vía SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}      # Tu IP Elástica: 44.214.67.2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}    # Tu llave devops.pem
          script: |
            mkdir -p ~/frontend-app && cd ~/frontend-app
            rm -rf *
            git clone -b deploy https://github.com/glenVon/Front_Eval2.git .
            docker compose down || true
            docker compose up -d --build
            docker image prune -f