name: CI/CD Frontend Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v3

      - name: Desplegar en EC2 Frontend vía SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}      # Tu IP Elástica: 44.214.67.2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}    # Tu llave devops.pem
          script: |
            # 1. Crear y asegurar la carpeta del proyecto
            mkdir -p ~/frontend-app && cd ~/frontend-app
            
            # 2. Limpiar contenido antiguo de forma segura
            rm -rf * .git
            
            # 3. Clonar el repositorio apuntando a la rama deploy
            git clone -b deploy https://github.com/glenVon/Front_Eval2.git .
            
            # 4. Orquestar el contenedor usando la sintaxis moderna (sin guion medio)
            docker compose down || true
            docker compose up -d --build
            
            # 5. Limpieza preventiva de almacenamiento
            docker image prune -f